# Generated by Django 4.1.4 on 2023-04-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_query',
            name='public',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
