# Generated by Django 4.0.4 on 2023-10-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_query', '0002_alter_filter_query_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter_query',
            name='date_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter_query',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
