pipeline {
    agent { 
        dockerfile {
            dir 'tests'
            filename 'Dockerfile'
        }
    }
    stages {
        stage('Unit Tests') {
            steps {
                dir('tests/unit/common/src') {
                    sh 'python3 test_manage_status.py'
                }
                dir('tests/unit/pipeline/sherlock') {
                    sh 'python3 test_sherlock_wrapper.py'
                }
                dir('tests/unit/pipeline/filter') {
                    sh 'python3 test_watchlist.py'
                }
            }
            post {
                always {
                    junit 'tests/unit/common/src/test-reports/*.xml'
                    junit 'tests/unit/pipeline/sherlock/test-reports/*.xml'
                    junit 'tests/unit/pipeline/filter/test-reports/*.xml'
                    deleteDir() /* clean up workspace */
                }
            }
        }
    }
}

