# Generated by Django 4.0.4 on 2022-12-19 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotators',
            fields=[
                ('topic', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('password', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('public', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annotators',
                'managed': True,
            },
        ),
    ]
