# Generated by Django 4.0.4 on 2023-10-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlist_active_alter_watchlist_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='date_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
