# Generated by Django 4.0.4 on 2022-12-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lasair', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='myqueries',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlistcones',
            name='wl',
        ),
        migrations.RemoveField(
            model_name='watchlists',
            name='user',
        ),
        migrations.DeleteModel(
            name='Annotators',
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
        migrations.DeleteModel(
            name='Myqueries',
        ),
        migrations.DeleteModel(
            name='WatchlistCones',
        ),
        migrations.DeleteModel(
            name='Watchlists',
        ),
    ]
