# Generated by Django 4.0.4 on 2023-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmap',
            name='public',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
